### ISSUE TITLE
Build error for esp-idf

### ISSUE THREAD

**Issue by wtakuo** [psg-titech/emfrp-repl#2]
The following error was reported when tried to build with esp-idf (v5.0-dirty).

```
% . esp/esp-idf/export.sh
% cd Work/FRP/emfrp-repl
% sh project/esp-idf/gen_parser.sh
% cd project/esp-idf
% idf.py set-target esp32
% idf.py build
...
In file included from /Users/takuo/Dropbox/Work/FRP/emfrp-repl/include/vm/exec.h:11,
                 from /Users/takuo/Dropbox/Work/FRP/emfrp-repl/src/vm/exec.c:8:
/Users/takuo/Dropbox/Work/FRP/emfrp-repl/src/vm/exec.c: In function 'exec_ast':
/Users/takuo/Dropbox/Work/FRP/emfrp-repl/include/vm/machine.h:131:35: error: 'state' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  131 |   self->stack->value.stack.length = state;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/Users/takuo/Dropbox/Work/FRP/emfrp-repl/src/vm/exec.c:376:17: note: 'state' was declared here
  376 |   stack_state_t state;
      |                 ^~~~~
cc1: some warnings being treated as errors
...
```

**Comment by puyogo-suzuki** [comment]
Fixed in 5cd9dedf0ed607e3a9782a9fe413e9a91a322748.
I recommend using v5.0 by `git switch v5.0` as it seems to report different errors.

**Comment by wtakuo** [comment]
Thanks. Now I can successfully build it and run it on my ESP32 DevkitC.
